# Generated by Django 6.0.5 on 2026-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publisher',
            field=models.CharField(default='me', max_length=200, verbose_name='publisher'),
        ),
    ]
